---
name: Get GitHub team members
description: Retrieve team members from a GitHub team
branding:
  icon: 'users'  
  color: 'yellow'
inputs:
  org:
    description: Name of the org
    required: true
    default: ${{ github.repository_owner }}
  team_slug:
    description: Slug of the team
    required: true
  role:
    description: 'Role of the member.  Must be one of: member, maintainer, all.'
    required: false
    default: all
  token: 
    description: GitHub token
    required: true
    default: ${{ github.token }}
outputs:
  data:
    description: Raw member data from GitHub API
    value: ${{ steps.get-members.outputs.data }}
  members:
    description: GitHub logins of team members
    value: ${{ steps.members.outputs.members }}
runs:
  using: composite
  steps:
    - name: get-team-members
      id: get-members
      shell: bash
      run: echo data=$(gh api --paginate -X GET /orgs/$ORG/teams/$TEAM_SLUG/members\?role=$ROLE | jq 'reduce inputs as $i (.; . += $i)') >> "$GITHUB_OUTPUT"
      env:
        ORG: ${{ inputs.org }}
        TEAM_SLUG: ${{ inputs.team_slug }}
        ROLE: ${{ inputs.role }}
        GH_TOKEN: ${{ inputs.token }}
    - id: members
      run: echo 'members=${{ join(fromJson(steps.get-members.outputs.data).*.login) }}' >> "$GITHUB_OUTPUT"
      shell: bash
